### PR TITLE
edx-downloader revamped with many new features!

### PR DESCRIPTION
**Pull request by SpyridonLaz**
Revamped with lots of new features!

- Now, subtitles (.srt filetype) can be downloaded whenever they are available !
- Added optional command arguments : 
1. `--debug`            (Default True) 
2. `--colored`          (Default True) 
3. `--results` (Default False) **NEW** The program will m process all the previously gathered results without Web Scraping will be skipped in this mode.

**New** Now, whole Dashboard will be parsed by Default. The user can choose to scrape one, many or all available/accessible courses that are found in your Dashboard. 
- A refined /folder/subfolder/file names and path structure was added. Files are now saved under **./ {course_name}/ {chapter_name}/**
- **New** Requests Session ,cookies will persist even after exit. no more unescessary logins.
- **New** Now parse results will be saved, both both positive and negative results. reparsing time decreases dramatically.
- **New** Downloading of videos can now be continued in case of interruption !!
- Fixed a bug where a download interruption would create an incomplete video to be detected as already downloaded during reparse.

### CODE REVIEW

**Comment by SpyridonLaz** [comment]
Harsh and honest criticism will be appreciated! ty

**Comment by rehmatworks** [comment]
I highly appreciate your effort and contribution, but this is a huge revamp. I'd like to know user feedback on whether they prefer a Selenium-based solution or not.

**Comment by SpyridonLaz** [comment]
Thank you for your kind feedback ! its my first contribution as a programmer and I do appreciate your recognition. 

 > I highly appreciate your effort and contribution, but this is a huge revamp. I'd like to know user feedback on whether they prefer a Selenium-based solution or not.

Regarding Selenium :
    I did consider it for quite some time, that's why it's not run by default,instead the user must use `--developent` arg to enable it. 
But I understand your point. So, I have a proposition to make : I make a new pull request without Selenium, we both review it, and when you (hopefully) accept it then I might make a new draft with Selenium and we hear feedback from other users? then if user feedback is positive we proceed, else we wont.

What do you think?

Thank you mr.Rehmat in advance and also thank you for inspiring me with your code.

**Comment by rehmatworks** [comment]
I feel proud to see you contributing to the open source. My only concern about Selenium is that users generally can't or don't want to download and configure selenium. But this is just a thought. Let's wait for a while and see if some of the users respond here. Maybe my code was really bad. I haven't been able to spend time on this and I'd obviously highly appreciate your contribution. Welcome to the world of open source contribution.

**Comment by rehmatworks** [comment]
As a side note, if you have the time and it's easy for you, I suggest that you should use [Typer](https://typer.tiangolo.com/) for this revamp. I have used that tool in some of the projects and it's really amazing. I have thoughts to rewrite this using Typer but if you can do that, I'd highly appreciate it.

**Comment by SpyridonLaz** [comment]
> I feel proud to see you contributing to the open source. My only concern about Selenium is that users generally can't or don't want to download and configure selenium. But this is just a thought. Let's wait for a while and see if some of the users respond here. Maybe my code was really bad. I haven't been able to spend time on this and I'd obviously highly appreciate your contribution. Welcome to the world of open source contribution.

I completely agree with you. Selenium is troublesome to configure and, to be fair, I did not want to use it at all. People just need something robust that **just works**, honestly.  
By default, `Requests` is being used, but for some dynamically loaded content (example: New York University Cybersecurity program) it was unavoidable. Ok lets see how it goes.

What is Typer about? Is it good? I will def check it out.

**Comment by SpyridonLaz** [comment]
Hey again Rehmat. check it out, i removed Selenium . I also added pdf screenshots! 
I hope you like it and accept my pull request!

**Comment by SpyridonLaz** [comment]
Do we have any progress on thr matter?

**Pull request closed without merging**
